app_id: 6L903538-42B1-4596-G479-BJ779F21A65D
publisher: Hiddify
publisher_url: https://github.com/hiddify/hiddify-next
display_name: Hiddify Next
executable_name: HiddifyNext.exe
output_base_file_name: HiddifyNext.exe
create_desktop_icon: true
install_dir_name: "{autopf64}\\hiddify"
setup_icon_file: ..\..\windows\runner\resources\app_icon.ico
locales:
  - en
  - fa
  - zh
  - ru
  - pt
  - tr
#script_template: inno_setup.sas